name: Naukri Automation

on:
  workflow_dispatch: # Trigger manually or schedule it
  schedule:
    - cron: '0 9 * * *' # Schedule at 9:00 AM daily

jobs:
  automate-naukri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Python version to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install pyautogui

    - name: Set up Selenium WebDriver
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/linux64/chromedriver-linux64.zip" -O chromedriver.zip
        unzip chromedriver.zip
        mv chromedriver-linux64 chromedriver
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chrome-headless-shell-linux64.zip" -O chrome-headless-shell.zip
        unzip chrome-headless-shell-linux64.zip
        mv chrome-headless-shell-linux64 chrome-headless-shell
        sudo mv chrome-headless-shell /usr/local/bin/
        sudo chmod +x /usr/local/bin/chrome-headless-shell
        chrome-headless-shell --version

    - name: Run Naukri Automation
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        RESUME_PATH: ./resources/Omkar_Aher_resume_5years.pdf # Relative path in the repository
      run: |
        python automate_naukri.py
