name: Naukri Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Schedule at 9:00 AM daily

jobs:
  automate-naukri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Chrome Version
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Installed Chrome version: ${CHROME_VERSION}"
        echo "CHROME_VERSION=${CHROME_VERSION}" >> $GITHUB_ENV

    - name: Check ChromeDriver Version
      run: |
        # Get ChromeDriver version (if it exists)
        CHROMEDRIVER_VERSION=$(chromedriver --version || echo "not_installed")
        echo "Installed ChromeDriver version: ${CHROMEDRIVER_VERSION}"
        echo "CHROMEDRIVER_VERSION=${CHROMEDRIVER_VERSION}" >> $GITHUB_ENV

    - name: Install ChromeDriver if Necessary
      run: |
        # Only install ChromeDriver if the version doesn't match
        if [ "$CHROMEDRIVER_VERSION" != "ChromeDriver ${CHROME_VERSION}" ]; then
          echo "ChromeDriver version does not match. Installing the correct version..."
          
          # Fetch the latest ChromeDriver version for the closest Chrome version
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" || echo "latest")
          echo "Chromedriver version to be installed: ${CHROMEDRIVER_VERSION}"
          
          if [ "$CHROMEDRIVER_VERSION" != "latest" ]; then
            # Download matching ChromeDriver
            wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
            unzip chromedriver.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
          else
            echo "Could not fetch a matching ChromeDriver version. Proceeding with available version."
          fi
        else
          echo "ChromeDriver version is already correct."
        fi

    - name: Verify Chrome and ChromeDriver Versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Naukri Automation
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        RESUME_PATH: ./resources/Omkar_Aher_resume_5years.pdf # Relative path in the repository
      run: |
        python automate_naukri.py
