name: Naukri Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Schedule at 9:00 AM daily

jobs:
  automate-naukri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Chrome Version
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Installed Chrome version: ${CHROME_VERSION}"
        echo "CHROME_VERSION=${CHROME_VERSION}" >> $GITHUB_ENV

    - name: Check ChromeDriver Version
      run: |
        # Get ChromeDriver version (if it exists)
        CHROMEDRIVER_VERSION=$(chromedriver --version || echo "not_installed")
        echo "Installed ChromeDriver version: ${CHROMEDRIVER_VERSION}"
        echo "CHROMEDRIVER_VERSION=${CHROMEDRIVER_VERSION}" >> $GITHUB_ENV

    - name: Remove Old ChromeDriver if Present
      run: |
        # Check if chromedriver exists and delete it if necessary
        if [ -f "/usr/local/bin/chromedriver" ]; then
          echo "Removing old chromedriver..."
          sudo rm /usr/local/bin/chromedriver
        fi

    - name: Install ChromeDriver Version 114.0.5735.90
      run: |
        # Fetch and install ChromeDriver version 114.0.5735.90
        CHROMEDRIVER_VERSION="114.0.5735.90"
        echo "Installing ChromeDriver version: ${CHROMEDRIVER_VERSION}"
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify Chrome and ChromeDriver Versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Naukri Automation
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        RESUME_PATH: ./resources/Omkar_Aher_resume_5years.pdf # Relative path in the repository
      run: |
        python automate_naukri.py
